@echo off
setlocal
REM ===================================================================================
REM  Keep the server's desktop clickable, without having to remember anything.
REM
REM  THE PROBLEM
REM  The commissioner drives FBPB3 with real mouse clicks, because it is a VB6 app with no
REM  API whose owner-drawn controls ignore posted messages. Real clicks need a desktop that
REM  Windows is actually rendering. When you close a Remote Desktop window, Windows LOCKS
REM  that session: processes keep running, but nothing renders and nothing can be clicked,
REM  so a sim fails at its next click.
REM
REM  tools\keep_session.bat fixes that by hand, but it disconnects you the moment you run it
REM  and only helps if you remember every single time.
REM
REM  WHAT THIS DOES INSTEAD
REM  Registers a scheduled task that fires when a remote session disconnects and hands that
REM  session back to the console, where it never locks and renders fine with no monitor.
REM  You just close the RDP window.
REM
REM  Run ONCE as Administrator.  Undo:
REM      schtasks /delete /tn "Cheezeyverse session keeper" /f
REM
REM  IF SERVERPC ALREADY HAS AN EQUIVALENT TASK, DO NOT INSTALL THIS ONE TOO. Two tasks both
REM  calling tscon on the same disconnect race each other. Check first:
REM      schtasks /query /fo list | findstr /I "keep desktop session keeper"
REM ===================================================================================

net session >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo   Must run as Administrator - registering a SYSTEM task needs it.
    echo.
    pause
    exit /b 1
)

set "DIR=%ProgramData%\Cheezeyverse"
set "HELPER=%DIR%\console_handoff.ps1"
if not exist "%DIR%" mkdir "%DIR%"

REM The helper is PowerShell, not batch, and that is deliberate. The obvious batch version
REM parses `query session` with tokens=1,2,3 and is wrong twice over: the "services 0 Disc"
REM row has a BLANK username, so its columns shift left and the state lands in token 3 and
REM matches - running tscon against session 0 - while a genuine "rdp-tcp#0 Server 1 Disc" row
REM puts the ID in token 3, so it never matches and the thing never fires at all. Column
REM positions in qwinsta output are not a reliable parse; regex on the whole line is.
> "%HELPER%" echo # Auto-generated by tools\install_session_keeper.bat. Hands a disconnected
>> "%HELPER%" echo # RDP session back to the console so the desktop keeps rendering.
>> "%HELPER%" echo $log = Join-Path $PSScriptRoot 'console_handoff.log'
>> "%HELPER%" echo Start-Sleep -Seconds 2
>> "%HELPER%" echo $rows = qwinsta 2^>$null ^| Select-Object -Skip 1
>> "%HELPER%" echo foreach ($row in $rows) {
>> "%HELPER%" echo   # id then state, with the session name and user name ahead of them however
>> "%HELPER%" echo   # they happen to be padded. Only a row with a real user is a candidate.
>> "%HELPER%" echo   if ($row -match '^\s*\S+\s+(\S+)\s+(\d+)\s+(\w+)') {
>> "%HELPER%" echo     $user = $Matches[1]; $id = $Matches[2]; $state = $Matches[3]
>> "%HELPER%" echo     if ($state -eq 'Disc' -and $user -notmatch '^\d+$') {
>> "%HELPER%" echo       $out = ^& "$env:windir\System32\tscon.exe" $id /dest:console 2^>^&1
>> "%HELPER%" echo       "$(Get-Date -f 'yyyy-MM-dd HH:mm:ss')  session $id ($user) -^> console (exit $LASTEXITCODE) $out" ^| Add-Content $log
>> "%HELPER%" echo       break
>> "%HELPER%" echo     }
>> "%HELPER%" echo   }
>> "%HELPER%" echo }

echo   helper written to %HELPER%

schtasks /query /tn "Cheezeyverse session keeper" >nul 2>&1
if not errorlevel 1 (
    echo   replacing the existing task
    schtasks /delete /tn "Cheezeyverse session keeper" /f >nul
)

schtasks /create ^
  /tn "Cheezeyverse session keeper" ^
  /tr "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File \"%HELPER%\"" ^
  /sc onevent ^
  /ec "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" ^
  /mo "*[System[Provider[@Name='Microsoft-Windows-TerminalServices-LocalSessionManager'] and EventID=24]]" ^
  /ru "SYSTEM" ^
  /rl HIGHEST ^
  /f

if errorlevel 1 (
    echo.
    echo   Could not register the task. keep_session.bat still works by hand, or reach the
    echo   machine with VNC / AnyDesk / Parsec instead of RDP - those mirror the console
    echo   session, so disconnecting from them never locks anything.
    echo.
    pause
    exit /b 1
)

echo.
echo  ================================================================
echo   Installed. Close the Remote Desktop window whenever you like;
echo   about two seconds later the session moves to the console and
echo   stays clickable, so a sim in progress keeps running.
echo.
echo   Log: %DIR%\console_handoff.log
echo.
echo   WHILE A SIM IS RUNNING AND YOU ARE CONNECTED:
echo     - do not MINIMIZE the Remote Desktop window. A minimized
echo       mstsc client stops the remote session rendering, and the
echo       clicks stop landing. Leave it open and visible.
echo     - do not let this machine sleep. Dropping RDP mid-sim moves
echo       the session to the console, changing the resolution.
echo  ================================================================
echo.
pause
