@echo off
setlocal
REM ===================================================================================
REM  Keep the server's desktop clickable, without having to remember anything.
REM
REM  THE PROBLEM
REM  The commissioner drives FBPB3 with real mouse clicks, because it is a VB6 app with no
REM  API whose owner-drawn controls ignore posted messages. Real clicks need a desktop that
REM  Windows is actually rendering. When you close a Remote Desktop window, Windows LOCKS
REM  that session: processes keep running, but nothing renders and nothing can be clicked,
REM  so a sim fails at its next click.
REM
REM  tools\keep_session.bat fixes that by hand, but it is brutal - it disconnects you the
REM  moment you run it, and you have to remember to run it every single time.
REM
REM  WHAT THIS DOES INSTEAD
REM  Registers a scheduled task that watches the Terminal Services log for "session has been
REM  disconnected" (event 24) and runs tscon itself, a second later. You just close the RDP
REM  window like normal. The session hands itself back to the console, where it never locks
REM  and renders fine with no monitor attached.
REM
REM  Run this ONCE, as Administrator. To undo:
REM      schtasks /delete /tn "Cheezeyverse session keeper" /f
REM ===================================================================================

net session >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo   Must run as Administrator - registering a SYSTEM task needs it.
    echo   Right-click this file and choose "Run as administrator".
    echo.
    pause
    exit /b 1
)

set "HELPER=%ProgramData%\Cheezeyverse\reconnect_to_console.bat"
if not exist "%ProgramData%\Cheezeyverse" mkdir "%ProgramData%\Cheezeyverse"

REM The helper itself. It finds whichever session is Disc(onnected) and moves it to the
REM console. Written out here rather than shipped in the repo so the task always points at a
REM fixed path that does not move if the repo does.
> "%HELPER%" echo @echo off
>> "%HELPER%" echo REM Auto-generated by tools\install_session_keeper.bat - see that file for why.
>> "%HELPER%" echo timeout /t 2 /nobreak ^>nul
>> "%HELPER%" echo for /f "skip=1 tokens=1,2,3" %%%%a in ('query session 2^^^>nul') do (
>> "%HELPER%" echo     if /I "%%%%c"=="Disc" "%%windir%%\System32\tscon.exe" %%%%b /dest:console
>> "%HELPER%" echo )

echo.
echo   helper written to %HELPER%
echo.

schtasks /query /tn "Cheezeyverse session keeper" >nul 2>&1
if not errorlevel 1 (
    echo   replacing the existing task
    schtasks /delete /tn "Cheezeyverse session keeper" /f >nul
)

schtasks /create ^
  /tn "Cheezeyverse session keeper" ^
  /tr "\"%HELPER%\"" ^
  /sc onevent ^
  /ec "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" ^
  /mo "*[System[Provider[@Name='Microsoft-Windows-TerminalServices-LocalSessionManager'] and EventID=24]]" ^
  /ru "SYSTEM" ^
  /rl HIGHEST ^
  /f

if errorlevel 1 (
    echo.
    echo   Could not register the task. You can still use tools\keep_session.bat by hand,
    echo   or reach the machine with VNC / AnyDesk / Parsec instead of RDP - those mirror
    echo   the console session, so disconnecting from them never locks anything.
    echo.
    pause
    exit /b 1
)

echo.
echo  ================================================================
echo   Installed.
echo.
echo   Close your Remote Desktop window whenever you like. About two
echo   seconds later the session moves itself to the console, where it
echo   stays unlocked and clickable - so a sim in progress keeps going.
echo.
echo   Test it: start a Sim Week, close the RDP window, reconnect a
echo   couple of minutes later and check the log kept moving.
echo.
echo   To remove:
echo     schtasks /delete /tn "Cheezeyverse session keeper" /f
echo  ================================================================
echo.
pause
