"""Copy the things that cannot be rebuilt onto a different drive, and prove the copy is good.

WHAT IS ACTUALLY AT RISK. Almost everything here is reproducible: the code and the game-line
archive are in git, the characters are in Supabase, the published site is on GitHub Pages, and
every page under a save's `html\\` is regenerated by the game on the next export. Three files per
league are not. `league.dat` IS the universe - every player, every rating, every result - and
FBPB3 has no other copy of it. `.env` holds keys that cannot be recovered from anywhere on this
machine, only reissued.

WHY OFF THIS DRIVE. Sim Week already backs a save up before it touches it, which is the right
guard against a bad write and no guard at all against the disk those backups live on. They sit
in `hoops-universe\\backups\\` on C:, beside the saves they protect - 288 folders and 1.8 GB of
them, every one lost with the drive.

VERIFIED, NOT ASSUMED. Every file is hashed at the source, copied, and hashed again at the
destination; a snapshot that does not match is deleted rather than kept, because a backup nobody
checked is a story about a backup. The hashes are written into the snapshot, so a restore can be
checked years later against what was actually read that day.

    python tools/offsite_backup.py              # take a snapshot, prune old ones
    python tools/offsite_backup.py --check      # say how fresh the newest one is, change nothing
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

DOCS = Path(r"C:\Users\Public\Documents\GDS\Fast Break Pro Basketball 3")
DEST = Path(r"D:\Cheezeyverse-backups")
# D: is a 20 TB pool and a snapshot is about 16 MB, so this is months of daily copies for the
# size of one video. The number is a retention policy, not a space limit.
KEEP = 60


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sources():
    """[(label, path)] - everything worth copying, newest truth first.

    The `html\\` folder of each save is deliberately NOT here. It is 600-odd pages the game
    rewrites from league.dat on every export, and copying it would make each snapshot forty
    times bigger to preserve something a single click regenerates.
    """
    out = []
    try:
        from commissioner.universe import config as cfg
        leagues = [(s.key, s.save_name) for s in cfg.LEAGUES]
    except Exception:
        leagues = [("prep", "CV_Prep"), ("college", "CV_College"), ("pro", "CV_Pro")]
    for key, save in leagues:
        for name in ("league.dat", "saveinfo.dat"):
            path = DOCS / "leaguedata" / save / name
            if path.exists():
                out.append((f"{save}/{name}", path))
    # The keys. A second copy of a secret on the same machine is not a new exposure - it is the
    # same disk permissions - and without it a rebuild cannot talk to Supabase or Discord at all.
    env = ROOT / ".env"
    if env.exists():
        out.append(("repo/.env", env))
    for name in ("manifest.json", "sim_runs.json"):
        path = ROOT / "universe" / name
        if path.exists():
            out.append((f"universe/{name}", path))
    history = ROOT / "universe" / "history"
    if history.exists():
        for path in sorted(history.glob("*.json")):
            out.append((f"universe/history/{path.name}", path))
    local = ROOT / "universe" / "local_store.json"
    if local.exists():
        out.append(("universe/local_store.json", local))
    return out


def snapshots(dest=DEST):
    """Existing snapshot folders, oldest first."""
    if not dest.exists():
        return []
    return sorted((d for d in dest.iterdir() if d.is_dir() and (d / "manifest.json").exists()),
                  key=lambda d: d.name)


def newest(dest=DEST):
    """(when, manifest) for the newest verified snapshot, or (None, None)."""
    for folder in reversed(snapshots(dest)):
        try:
            payload = json.loads((folder / "manifest.json").read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        when = payload.get("taken_at")
        if when:
            return datetime.fromisoformat(when), payload
    return None, None


def take(dest=DEST, keep=KEEP, log=print):
    """One verified snapshot. Returns its folder, or None if nothing could be copied."""
    if not dest.parent.exists() and not dest.exists():
        log(f"the backup drive is not there ({dest.drive}\\) - nothing was copied")
        return None
    items = sources()
    if not items:
        log("found nothing to back up, which is itself wrong - check the save paths")
        return None
    # NEVER REUSE AN EXISTING FOLDER. The name is a timestamp to the second, so two snapshots
    # taken in the same second - a retry, a hand-run next to the daily task - would land in one
    # folder, and the cleanup below would then delete a GOOD snapshot to tidy up a failed one.
    # Found by the test that took five snapshots in a loop. Claiming a fresh folder is also what
    # makes the rmtree on failure safe: we only ever remove one we created here.
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    folder, n = dest / stamp, 1
    while folder.exists():
        n += 1
        folder = dest / f"{stamp}-{n}"
    folder.mkdir(parents=True)
    manifest, copied, total = [], 0, 0
    try:
        for label, path in items:
            target = folder / label.replace("/", "__")
            before = sha256(path)
            shutil.copy2(path, target)
            after = sha256(target)
            if before != after:
                raise OSError(f"{label} did not survive the copy - hashes differ")
            size = target.stat().st_size
            manifest.append({"label": label, "source": str(path), "bytes": size,
                             "sha256": after})
            copied += 1
            total += size
        (folder / "manifest.json").write_text(json.dumps({
            "taken_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "machine": _machine(),
            "files": manifest,
        }, indent=1), encoding="utf-8")
    except Exception as exc:                                     # noqa: BLE001
        # A half-written snapshot is worse than none: it looks like a backup in every listing.
        log(f"the snapshot failed ({exc}); removing the partial copy")
        shutil.rmtree(folder, ignore_errors=True)
        return None
    log(f"{copied} file(s), {total / 1e6:.1f} MB -> {folder}")
    _prune(dest, keep, log)
    return folder


def _machine():
    import os
    return os.environ.get("COMPUTERNAME", "")


def _prune(dest, keep, log):
    old = snapshots(dest)[:-keep] if keep > 0 else []
    for folder in old:
        shutil.rmtree(folder, ignore_errors=True)
    if old:
        log(f"pruned {len(old)} snapshot(s) older than the last {keep}")


def check(dest=DEST, log=print):
    """Report on the newest snapshot. 0 if it is fresh, 1 if it is stale or missing."""
    when, payload = newest(dest)
    if not when:
        log(f"NO BACKUP at {dest} - run: python tools/offsite_backup.py")
        return 1
    age = (datetime.now(timezone.utc) - when).total_seconds() / 3600
    files = len(payload.get("files") or [])
    size = sum(f.get("bytes", 0) for f in payload.get("files") or [])
    log(f"newest backup {age:.1f} h old: {files} files, {size / 1e6:.1f} MB, {dest}")
    if age > 48:
        log("that is older than two days - the daily task may not be running")
        return 1
    return 0


def main():
    if "--check" in sys.argv:
        return check()
    folder = take()
    return 0 if folder else 1


if __name__ == "__main__":
    raise SystemExit(main())
